apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-transcriber
  namespace: meetgeek
spec:
  scaleTargetRef:
    name: celery-transcriber
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        host: amqp://meetgeek:meetgeek@rabbitmq.meetgeek.svc.cluster.local:5672/
        queueName: meeting-transcription
        mode: QueueLength
        value: "4"
        activationValue: "1"
