apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: temporal-worker
  namespace: meetgeek
spec:
  scaleTargetRef:
    name: temporal-worker
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.meetgeek.svc.cluster.local:9090
        query: sum(increase(action{action_type="grpc_StartWorkflowExecution",namespace="default"}[1m]))
        threshold: "5"
        activationThreshold: "1"
